/**
 * SoundFont 2 (SF2) Binary Builder
 * Compiles AudioBuffer samples into a valid RIFF sfbk SoundFont 2.04 file
 * Also exports SFZ format text files.
 */
import { SF2Bank, SF2Sample } from '../types';

export function buildSF2Binary(
  bankOrName: SF2Bank | string,
  samplesInput?: SF2Sample[],
  authorInput = 'StemStudio SF2 Builder'
): Uint8Array {
  let bankName: string;
  let samples: SF2Sample[];
  let author: string;

  if (typeof bankOrName === 'string') {
    bankName = bankOrName;
    samples = samplesInput || [];
    author = authorInput;
  } else {
    bankName = bankOrName.name || 'SoundFont Bank';
    samples = bankOrName.presets.flatMap(p => p.instruments.flatMap(i => i.samples));
    author = bankOrName.author || 'StemStudio SF2 Builder';
  }

  if (samples.length === 0) {
    throw new Error('Cannot build SoundFont without any samples.');
  }

  // 1. Prepare PCM sample data
  // The SF2 spec requires 46 zero samples padding after every sample header
  const PADDING_SAMPLES = 46;
  const sampleDataParts: Int16Array[] = [];
  const shdrRecords: {
    name: string;
    start: number;
    end: number;
    startLoop: number;
    endLoop: number;
    sampleRate: number;
    rootKey: number;
    fineCorrection: number;
  }[] = [];

  let currentSampleOffset = 0;

  for (let sIdx = 0; sIdx < samples.length; sIdx++) {
    const s = samples[sIdx];
    const channelData = s.audioBuffer.getChannelData(0);
    const sampleLen = channelData.length;

    // Convert Float32 to 16-bit signed PCM
    const pcm = new Int16Array(sampleLen + PADDING_SAMPLES);
    for (let i = 0; i < sampleLen; i++) {
      const val = Math.max(-1, Math.min(1, channelData[i]));
      pcm[i] = val < 0 ? val * 0x8000 : val * 0x7fff;
    }
    // padding zeroes are already 0 in Int16Array

    sampleDataParts.push(pcm);

    const start = currentSampleOffset;
    const end = start + sampleLen;
    const startLoop = s.loopMode ? start + Math.min(s.loopStart, sampleLen - 2) : start;
    const endLoop = s.loopMode ? start + Math.min(s.loopEnd, sampleLen - 1) : end;

    shdrRecords.push({
      name: (s.name || `Sample_${sIdx + 1}`).slice(0, 19),
      start,
      end,
      startLoop,
      endLoop,
      sampleRate: s.sampleRate || 44100,
      rootKey: s.rootKey,
      fineCorrection: s.fineTune
    });

    currentSampleOffset += pcm.length;
  }

  // Final terminal sample "EOS"
  const eosPcm = new Int16Array(PADDING_SAMPLES);
  sampleDataParts.push(eosPcm);

  // Total PCM bytes in sdta
  let totalPcmSamples = 0;
  for (const part of sampleDataParts) totalPcmSamples += part.length;
  const smplChunkSize = totalPcmSamples * 2;

  // 2. Build INFO chunk
  const infoData: Uint8Array[] = [];
  infoData.push(createSubChunk('ifil', new Uint8Array([2, 0, 4, 0]))); // v2.04
  infoData.push(createStringSubChunk('isng', 'EMU8000'));
  infoData.push(createStringSubChunk('INAM', bankName || 'SoundFont Bank'));
  infoData.push(createStringSubChunk('ISFT', author));
  infoData.push(createStringSubChunk('ICMT', 'Generated by StemStudio SF2 DAW Suite'));
  const infoChunk = createListChunk('INFO', mergeUint8Arrays(infoData));

  // 3. Build sdta chunk
  const smplHeader = new Uint8Array(8);
  const smplView = new DataView(smplHeader.buffer);
  writeAscii(smplView, 0, 'smpl');
  smplView.setUint32(4, smplChunkSize, true);

  const mergedPcm = new Uint8Array(smplChunkSize);
  let pcmByteOffset = 0;
  for (const part of sampleDataParts) {
    const byteView = new Uint8Array(part.buffer, part.byteOffset, part.byteLength);
    mergedPcm.set(byteView, pcmByteOffset);
    pcmByteOffset += byteView.length;
  }
  const sdtaChunk = createListChunk('sdta', mergeUint8Arrays([smplHeader, mergedPcm]));

  // 4. Build pdta chunk:
  // phdr, pbag, pmod, pgen, inst, ibag, imod, igen, shdr
  const N = samples.length;

  // Preset Header (phdr): 2 records (1 preset + 1 terminal EOP)
  const phdrBytes = new Uint8Array(38 * 2);
  const phdrView = new DataView(phdrBytes.buffer);
  writePaddedAscii(phdrView, 0, (bankName || 'Preset 1').slice(0, 19), 20);
  phdrView.setUint16(20, 0, true); // preset 0
  phdrView.setUint16(22, 0, true); // bank 0
  phdrView.setUint16(24, 0, true); // preset bag index 0
  phdrView.setUint32(26, 0, true); // morph
  phdrView.setUint32(30, 0, true);
  phdrView.setUint32(34, 0, true);

  // Terminal EOP
  writePaddedAscii(phdrView, 38, 'EOP', 20);
  phdrView.setUint16(38 + 20, 0, true);
  phdrView.setUint16(38 + 22, 0, true);
  phdrView.setUint16(38 + 24, 1, true); // points to pbag 1

  // Preset Bag (pbag): 2 records
  const pbagBytes = new Uint8Array(4 * 2);
  const pbagView = new DataView(pbagBytes.buffer);
  pbagView.setUint16(0, 0, true); // pgen index 0
  pbagView.setUint16(2, 0, true); // pmod index 0
  pbagView.setUint16(4, 1, true); // terminal pgen
  pbagView.setUint16(6, 0, true);

  // Preset Modulator (pmod): 1 terminal record
  const pmodBytes = new Uint8Array(10);

  // Preset Generator (pgen): 2 records (gen 41 = instrument index 0, + terminal gen 0)
  const pgenBytes = new Uint8Array(4 * 2);
  const pgenView = new DataView(pgenBytes.buffer);
  pgenView.setUint16(0, 41, true); // gen Oper = 41 (instrument)
  pgenView.setUint16(2, 0, true); // instrument index 0
  pgenView.setUint16(4, 0, true);
  pgenView.setUint16(6, 0, true);

  // Instrument Header (inst): 2 records (1 inst + 1 terminal EOI)
  const instBytes = new Uint8Array(22 * 2);
  const instView = new DataView(instBytes.buffer);
  writePaddedAscii(instView, 0, (bankName || 'Inst 1').slice(0, 19), 20);
  instView.setUint16(20, 0, true); // ibag index 0

  writePaddedAscii(instView, 22, 'EOI', 20);
  instView.setUint16(22 + 20, N, true); // terminal ibag index

  // Instrument Bag (ibag): (N + 1) records (1 per sample zone + 1 terminal)
  const ibagBytes = new Uint8Array(4 * (N + 1));
  const ibagView = new DataView(ibagBytes.buffer);
  const GENS_PER_ZONE = 3; // keyRange (43), overridingRootKey (58), sampleID (53)
  for (let i = 0; i <= N; i++) {
    ibagView.setUint16(i * 4, i * GENS_PER_ZONE, true); // igen index
    ibagView.setUint16(i * 4 + 2, 0, true); // imod index
  }

  // Instrument Modulator (imod): 1 terminal record
  const imodBytes = new Uint8Array(10);

  // Instrument Generator (igen): (N * GENS_PER_ZONE + 1) records
  const igenTotalRecords = N * GENS_PER_ZONE + 1;
  const igenBytes = new Uint8Array(4 * igenTotalRecords);
  const igenView = new DataView(igenBytes.buffer);

  let genPos = 0;
  for (let i = 0; i < N; i++) {
    const s = samples[i];
    // Generator 43: keyRange [low, high]
    igenView.setUint16(genPos, 43, true);
    igenView.setUint8(genPos + 2, s.keyRange[0]);
    igenView.setUint8(genPos + 3, s.keyRange[1]);
    genPos += 4;

    // Generator 58: overridingRootKey
    igenView.setUint16(genPos, 58, true);
    igenView.setUint16(genPos + 2, s.rootKey, true);
    genPos += 4;

    // Generator 53: sampleID
    igenView.setUint16(genPos, 53, true);
    igenView.setUint16(genPos + 2, i, true);
    genPos += 4;
  }
  // Terminal record
  igenView.setUint16(genPos, 0, true);
  igenView.setUint16(genPos + 2, 0, true);

  // Sample Headers (shdr): (N + 1) records
  const shdrBytes = new Uint8Array(46 * (N + 1));
  const shdrView = new DataView(shdrBytes.buffer);

  for (let i = 0; i < N; i++) {
    const rec = shdrRecords[i];
    const off = i * 46;
    writePaddedAscii(shdrView, off, rec.name, 20);
    shdrView.setUint32(off + 20, rec.start, true);
    shdrView.setUint32(off + 24, rec.end, true);
    shdrView.setUint32(off + 28, rec.startLoop, true);
    shdrView.setUint32(off + 32, rec.endLoop, true);
    shdrView.setUint32(off + 36, rec.sampleRate, true);
    shdrView.setUint8(off + 40, rec.rootKey);
    shdrView.setInt8(off + 41, rec.fineCorrection);
    shdrView.setUint16(off + 42, 0, true); // sampleLink
    shdrView.setUint16(off + 44, 1, true); // monoSample
  }

  // Terminal EOS record
  const eosOff = N * 46;
  writePaddedAscii(shdrView, eosOff, 'EOS', 20);
  shdrView.setUint32(eosOff + 20, currentSampleOffset, true);
  shdrView.setUint32(eosOff + 24, currentSampleOffset, true);
  shdrView.setUint32(eosOff + 28, 0, true);
  shdrView.setUint32(eosOff + 32, 0, true);
  shdrView.setUint32(eosOff + 36, 44100, true);
  shdrView.setUint8(eosOff + 40, 60);
  shdrView.setInt8(eosOff + 41, 0);
  shdrView.setUint16(eosOff + 42, 0, true);
  shdrView.setUint16(eosOff + 44, 0, true);

  const pdtaSubChunks: Uint8Array[] = [
    createSubChunk('phdr', phdrBytes),
    createSubChunk('pbag', pbagBytes),
    createSubChunk('pmod', pmodBytes),
    createSubChunk('pgen', pgenBytes),
    createSubChunk('inst', instBytes),
    createSubChunk('ibag', ibagBytes),
    createSubChunk('imod', imodBytes),
    createSubChunk('igen', igenBytes),
    createSubChunk('shdr', shdrBytes)
  ];
  const pdtaChunk = createListChunk('pdta', mergeUint8Arrays(pdtaSubChunks));

  // 5. Wrap inside top-level RIFF sfbk
  const totalRiffLength = 4 + infoChunk.length + sdtaChunk.length + pdtaChunk.length;
  const riffHeader = new Uint8Array(12);
  const riffView = new DataView(riffHeader.buffer);
  writeAscii(riffView, 0, 'RIFF');
  riffView.setUint32(4, totalRiffLength, true);
  writeAscii(riffView, 8, 'sfbk');

  const finalSF2 = mergeUint8Arrays([riffHeader, infoChunk, sdtaChunk, pdtaChunk]);
  return finalSF2;
}

/**
 * Export SFZ instrument format mapping text
 */
export function generateSFZText(bankName: string, samples: SF2Sample[]): string {
  let sfz = `// SFZ Definition for ${bankName}\n`;
  sfz += `// Generated by StemStudio SF2 Suite\n\n`;
  sfz += `<control>\ndefault_path=samples/\n\n<global>\n`;

  for (const s of samples) {
    sfz += `<region>\n`;
    sfz += `sample=${s.name.replace(/\s+/g, '_')}.wav\n`;
    sfz += `key=${s.rootKey}\n`;
    sfz += `lokey=${s.keyRange[0]} hikey=${s.keyRange[1]}\n`;
    sfz += `pitch_keycenter=${s.rootKey}\n`;
    if (s.fineTune !== 0) sfz += `tune=${s.fineTune}\n`;
    if (s.loopMode) {
      sfz += `loop_mode=loop_continuous\n`;
      sfz += `loop_start=${s.loopStart}\n`;
      sfz += `loop_end=${s.loopEnd}\n`;
    } else {
      sfz += `loop_mode=no_loop\n`;
    }
    sfz += `ampeg_attack=${s.attack}\n`;
    sfz += `ampeg_decay=${s.decay}\n`;
    sfz += `ampeg_sustain=${Math.round(s.sustain * 100)}\n`;
    sfz += `ampeg_release=${s.release}\n\n`;
  }
  return sfz;
}

// Helpers for binary RIFF chunk construction
function createSubChunk(id: string, data: Uint8Array): Uint8Array {
  const pad = data.length % 2 !== 0 ? 1 : 0;
  const header = new Uint8Array(8);
  const view = new DataView(header.buffer);
  writeAscii(view, 0, id);
  view.setUint32(4, data.length, true);

  if (pad === 0) {
    return mergeUint8Arrays([header, data]);
  }
  const paddingByte = new Uint8Array(1);
  return mergeUint8Arrays([header, data, paddingByte]);
}

function createStringSubChunk(id: string, str: string): Uint8Array {
  const bytes = new Uint8Array(str.length + 1); // null-terminated
  for (let i = 0; i < str.length; i++) bytes[i] = str.charCodeAt(i);
  bytes[str.length] = 0;
  return createSubChunk(id, bytes);
}

function createListChunk(listType: string, contents: Uint8Array): Uint8Array {
  const pad = (contents.length + 4) % 2 !== 0 ? 1 : 0;
  const header = new Uint8Array(12);
  const view = new DataView(header.buffer);
  writeAscii(view, 0, 'LIST');
  view.setUint32(4, 4 + contents.length + pad, true);
  writeAscii(view, 8, listType);

  if (pad === 0) {
    return mergeUint8Arrays([header, contents]);
  }
  return mergeUint8Arrays([header, contents, new Uint8Array(1)]);
}

function mergeUint8Arrays(arrays: Uint8Array[]): Uint8Array {
  let totalLength = 0;
  for (const arr of arrays) totalLength += arr.length;
  const merged = new Uint8Array(totalLength);
  let offset = 0;
  for (const arr of arrays) {
    merged.set(arr, offset);
    offset += arr.length;
  }
  return merged;
}

function writeAscii(view: DataView, offset: number, str: string): void {
  for (let i = 0; i < str.length; i++) {
    view.setUint8(offset + i, str.charCodeAt(i));
  }
}

function writePaddedAscii(view: DataView, offset: number, str: string, totalLen: number): void {
  for (let i = 0; i < totalLen; i++) {
    view.setUint8(offset + i, i < str.length ? str.charCodeAt(i) : 0);
  }
}
